// Compila opaque-ke a WASM y lo deja DENTRO de un módulo JS.
//
// Un solo archivo y no un `.wasm` aparte por dos motivos: el vault se distribuye como
// ejecutable único (SEA), donde no se puede ir a buscar un archivo al lado, y la extensión y
// la pestaña tampoco tienen por qué saber dónde está. Se paga en tamaño (base64, +33 %).
//
// Salida en `build/` (no se commitea; lo arma CI antes de probar y de publicar):
//   build/opaque.js       el pegamento de wasm-bindgen (target web)
//   build/wasm-bytes.js   el WASM en base64
//   build/wasm.sha256     la huella del WASM, para comparar compilaciones
import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const wasmDir = join(root, 'wasm')
const out = join(root, 'build')

// wasm-bindgen exige que la CLI y el crate sean LA MISMA versión; si no, el pegamento no
// casa con el binario y falla al cargar, lejos de aquí.
const cargo = readFileSync(join(wasmDir, 'Cargo.toml'), 'utf8')
const pinned = /wasm-bindgen\s*=\s*"=([\d.]+)"/.exec(cargo)?.[1]
if (!pinned) throw new Error('build: wasm-bindgen must be pinned with "=x.y.z" in wasm/Cargo.toml')
const cli = execFileSync('wasm-bindgen', ['--version'], { encoding: 'utf8' }).trim().split(/\s+/)[1]
if (cli !== pinned) {
  throw new Error(`build: wasm-bindgen CLI is ${cli} but the crate pins ${pinned} — cargo install wasm-bindgen-cli --version ${pinned} --locked`)
}

execFileSync('cargo', ['build', '--release', '--locked', '--target', 'wasm32-unknown-unknown'], { cwd: wasmDir, stdio: 'inherit' })
const artifact = join(wasmDir, 'target', 'wasm32-unknown-unknown', 'release', 'dotrino_opaque.wasm')

rmSync(out, { recursive: true, force: true })
mkdirSync(out, { recursive: true })
execFileSync('wasm-bindgen', ['--target', 'web', '--no-typescript', '--out-dir', out, '--out-name', 'opaque', artifact], { stdio: 'inherit' })

const wasm = readFileSync(join(out, 'opaque_bg.wasm'))
const sha = createHash('sha256').update(wasm).digest('hex')
writeFileSync(join(out, 'wasm-bytes.js'), `// Generated by scripts/build.mjs — do not edit.\nexport default '${wasm.toString('base64')}'\n`)
writeFileSync(join(out, 'wasm.sha256'), `${sha}  opaque_bg.wasm\n`)
rmSync(join(out, 'opaque_bg.wasm'))
console.log(`build: wasm ${wasm.length} bytes, sha256 ${sha}`)
